services:

  mysql_db1: 
   image: mysql:8.0
   restart: always  # Ensure the service restarts automatically if it fails
   container_name: mysql_db1
   environment:
     MYSQL_HOST: mysql_db1
     MYSQL_ROOT_PASSWORD: gyaurocks99
     MYSQL_DATABASE: stream_db
     MYSQL_USER: streamuser
     MYSQL_PASSWORD: myuserpass
   ports: 
     - 3307:3306
   volumes:
       - mysql_data1:/var/lib/mysql
       - ./include/mysql_setup.sql:/docker-entrypoint-initdb.d/mysql_setup.sql
   command: >
     --init-file=/docker-entrypoint-initdb.d/mysql_setup.sql
   networks:
      - airflow_etl
      # - default  # Keep it on the default network too if needed

  postgres-db:
    container_name: redshift
    image: postgres:15  # Use Postgres version 15
    restart: always  # Ensure the service restarts automatically if it fails
    environment:
      POSTGRES_USER: redshift_user  # Custom Postgres username
      POSTGRES_PASSWORD: pass_word    #  password for Postgres
      POSTGRES_DB: redshift_db      # Custom default database
      PGSSLMODE: disable
    ports:
      - "5435:5432"  # Map local port 5435 to container's port 5432
    volumes:
      - postgres_data2:/var/lib/postgresql/data  # Persistent volume for Postgres data
      - ./db/postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql  # Custom init SQL script
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redshift_user -d redshift_db"]  # Health check to ensure Postgres is ready
      interval: 5s  # Check every 5 seconds
      timeout: 5s   # Timeout after 5 seconds
      retries: 10   # Retry 10 times before marking the service as unhealthy
    networks:
      - airflow_etl  # Connect the service to the custom network


volumes:
  mysql_data1:  
  postgres_data2:


  
networks:
  airflow:
    external: true
    # name: labs_209eb7_airflow